# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job1
  displayName: "First Job"
  steps:
  - script: echo "This is Job 1 - Step 1"
    displayName: "Run Job1 Step1"

  - script: echo "Job 1 completed!"
    displayName: "Run Job1 Step2"

- job: Job2
  displayName: "Second Job"
  dependsOn: Job1   # 👈 makes Job2 wait until Job1 finishes
  steps:
  - script: echo "This is Job 2 - Step 1"
    displayName: "Run Job2 Step1"

  - script: echo "Job 2 completed!"
    displayName: "Run Job2 Step2"






