# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
#trigger:
#- main
#
#pool:
#  vmImage: ubuntu-latest
#
#steps:
#- script: echo Hello, world,change!
#  displayName: 'Run a one-line script'
#
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  # Step 1: Install Terraform
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.6.0'

  # Step 2: Start LocalStack in Docker
  - script: |
      docker run -d -p 4566:4566 localstack/localstack
      sleep 10   # wait for LocalStack to fully start
    displayName: 'Start LocalStack'

  # Step 3: Terraform Init
  - script: terraform init
    displayName: 'Terraform Init'

  # Step 4: Terraform Plan
  - script: terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  # Step 5: Terraform Apply
  - script: terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'

