# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'commentservice'
  imageTag: '$(Build.BuildId)'

steps:
# -------------------------
# Step 1: Install Docker
# -------------------------
- script: |
    sudo apt-get update
    sudo apt-get install -y docker.io conntrack curl apt-transport-https
    docker --version
  displayName: 'Install Docker'

# -------------------------
# Step 2: Build Docker Image
# -------------------------
- script: |
    docker build -t $(imageName):$(imageTag) .
  displayName: 'Build Docker Image'

# -------------------------
# Step 3: Install Minikube and kubectl
# -------------------------
- script: |
    # Install Minikube
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    chmod +x minikube-linux-amd64
    sudo mv minikube-linux-amd64 /usr/local/bin/minikube
    minikube version

    # Install kubectl
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/
    kubectl version --client
  displayName: 'Install Minikube and kubectl'

# -------------------------
# Step 4: Start Minikube
# -------------------------
- script: |
    minikube start --driver=docker
    kubectl cluster-info
  displayName: 'Start Minikube Cluster'

# -------------------------
# Step 5: Load Docker Image into Minikube
# -------------------------
- script: |
    minikube image load $(imageName):$(imageTag)
  displayName: 'Load Docker Image into Minikube'

# -------------------------
# Step 6: Update Kubernetes deployment
# -------------------------
- script: |
    sed -i "s|image:.*|image: $(imageName):$(imageTag)|g" k8s/deployment.yaml
  displayName: 'Update K8S deployment image'

# -------------------------
# Step 7: Deploy to Minikube
# -------------------------
- script: |
    kubectl apply -f k8s/deployment.yaml
    kubectl apply -f k8s/service.yaml
    kubectl get pods -A
  displayName: 'Deploy App to Minikube'

