# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Install Terraform manually
- script: |
    curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
  displayName: 'Install Terraform'

# Step 2: Run LocalStack in Docker
- task: Docker@2
  displayName: 'Run LocalStack'
  inputs:
    command: 'run'
    arguments: '-d -p 4566:4566 localstack/localstack'

# Step 3: Terraform Init
- script: terraform init
  displayName: 'Terraform Init'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

# Step 4: Terraform Plan
- script: terraform plan -out=tfplan
  displayName: 'Terraform Plan'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

# Step 5: Terraform Apply
- script: terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
  workingDirectory: '$(System.DefaultWorkingDirectory)'


