# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# -------------------------
# Step 1: Install Terraform
# -------------------------
steps:
- script: |
    curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
  displayName: 'Install Terraform'

# -------------------------
# Step 2: Run LocalStack in Docker
# -------------------------
- task: Docker@2
  displayName: 'Run LocalStack'
  inputs:
    command: 'run'
    arguments: '-d -p 4566:4566 localstack/localstack'

# -------------------------
# Step 3: Terraform Init
# -------------------------
- script: terraform init
  displayName: 'Terraform Init'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

# -------------------------
# Step 4: Terraform Plan
# -------------------------
- script: terraform plan -out=tfplan
  displayName: 'Terraform Plan'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

# -------------------------
# Step 5: Terraform Apply
# -------------------------
- script: terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

# -------------------------
# Step 6: Install Minikube & kubectl
# -------------------------
- script: |
    sudo apt-get update
    sudo apt-get install -y conntrack curl apt-transport-https
    # Install Minikube
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    chmod +x minikube-linux-amd64
    sudo mv minikube-linux-amd64 /usr/local/bin/minikube
    minikube version
    # Install kubectl
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/
    kubectl version --client
  displayName: 'Install Minikube and kubectl'

# -------------------------
# Step 7: Start Minikube Cluster
# -------------------------
- script: |
    minikube start --driver=docker
    kubectl cluster-info
  displayName: 'Start Minikube Cluster'

# -------------------------
# Step 8: Deploy Kubernetes manifests
# -------------------------
- script: |
    kubectl apply -f k8s/deployment.yaml
    kubectl apply -f k8s/service.yaml
    kubectl get pods -A
  displayName: 'Deploy App to Minikube'

