# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'vakdevi/comment-service-devops'

stages:
- stage: Build
  displayName: Build and push Docker image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: 'vakdevi-docker-hub'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

- stage: Deploy
  displayName: Deploy to Minikube
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    # -------------------------
    # Step 1: Install Minikube & kubectl
    # -------------------------
    - script: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube-linux-amd64
        sudo mv minikube-linux-amd64 /usr/local/bin/minikube
        minikube version

        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        kubectl version --client
      displayName: Install Minikube & kubectl

    # -------------------------
    # Step 2: Start Minikube
    # -------------------------
    - script: |
        minikube start --driver=docker
        kubectl cluster-info
      displayName: Start Minikube Cluster

    # -------------------------
    # Step 3: Pull image from Docker Hub into Minikube
    # -------------------------
    - script: |
        minikube image pull $(imageName):$(tag)
      displayName: Load image into Minikube

    # -------------------------
    # Step 4: Update K8S manifests
    # -------------------------
    - script: |
        sed -i "s|image:.*|image: $(imageName):$(tag)|g" commentservice/k8s/deployment.yaml
      displayName: Update K8S deployment image

    # -------------------------
    # Step 5: Deploy to Minikube
    # -------------------------
    - script: |
        kubectl apply -f commentservice/k8s/deployment.yaml
        kubectl apply -f commentservice/k8s/service.yaml
        kubectl get pods -A
      displayName: Deploy App to Minikube
